name: TKPSS Website Spider

on:
  schedule:
    - cron: '0 0 15 * *' # 每个月的15日0点（UTC时间）执行
  workflow_dispatch: # 允许手动触发

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # 选择你需要的 Python 版本

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Run Python Crawler
    #   run: |
    #     python crawler.py

    - name: Greet and List
      run: |
        echo "Hello World!"
        echo -e "\n"

        pwd
        echo -e "\n"

        ls
        echo -e "\n"

        cd ".github/workflows"
        ls
        echo -e "\n"

        cd ../..
        ls